from pydantic import BaseModel, Field

class PromptResponse(BaseModel):
    """
    Response model for JD generation.

    Fields:
    - input: The original text prompt sent by the user.
    - jd_markdown: The generated job description, formatted in Markdown.
    """

    input: str = Field(
        ...,
        title="Prompt Input",
        description="The original job request prompt submitted by the user."
    )

    jd_markdown: str = Field(
        ...,
        title="Generated JD (Markdown)",
        description="The job description generated by the LLM in Markdown format."
    )
